# Generated by Django 4.1.6 on 2023-02-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('announcement', models.CharField(max_length=256, verbose_name='Announcement')),
                ('anons', models.TextField(verbose_name='Article')),
                ('date_article', models.DateTimeField(verbose_name='Publication date')),
            ],
        ),
    ]
